apiVersion: v1
kind: Service
metadata:
  name: planner
  labels: { { - include "planner.labels" . | nindent 4 } }
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app.kubernetes.io/name: planner
    app.kubernetes.io/instance: { { .Release.Name } }
  type: ClusterIP
  clusterIP: 10.152.1.5
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
