user:
  api/v1/events:
    "read:own": ["*"]
    "create:own": ["*"]
    "update:own": ["*"]
  api/v1/events/{event_id}:
    "delete:own": ["*"]
admin:
  api/v1/events:
    "read:any": ["*"]
    "create:any": ["*"]
    "update:any": ["*"]
  api/v1/events/{event_id}:
    "delete:any": ["*"]
